### ISSUE TITLE
Update version

### ISSUE THREAD

**Issue by MartinIIOT** [flathub/cc.arduino.arduinoide#30]
Hello,
is it possible to update Flatpak package (https://flathub.org/apps/details/cc.arduino.arduinoide) to 1.8.15 and distribute every latest version to this repository?

Thank you

**Comment by A6GibKm** [comment]
Yes, of course. I am currently a bit low on time, this would be an easy (but somewhat tedious¹) contribution if you want to try it. It is basically replacing https://github.com/flathub/cc.arduino.arduinoide/blob/master/cc.arduino.arduinoide.json#L86 with the correct number and sha256sum, and repeat that for any modules that are required by the IDE.

1. This is due to the large amount of dependencies.

**Comment by MartinIIOT** [comment]
Thanks for your reply. And it is possible to write short manual how to build it (I can try contribute)?

**Comment by A6GibKm** [comment]
First you need to get a bit familiarized with `flatpak-builder`, a naive but effective way to build this would be to go to the [manifest](https://github.com/flathub/cc.arduino.arduinoide/blob/master/cc.arduino.arduinoide.json) and update [L86](https://github.com/flathub/cc.arduino.arduinoide/blob/master/cc.arduino.arduinoide.json#L86) both with the new url and sha256sum for the tar.xz, then run 
```
flatpak-builder builddir cc.arduino.arduinoide.json --force-clean --user --install
```
where the last 2 flags tell that you want to install it (to test it) as an user if it succeeds. The build most likely than not will fail telling you that module X with version Y was not found and you will have to update that as well on the manifest, then repeat. There should be somewhere a place with the new dependencies required for the version, but I don't remember where it was.

> can try contribute
Please do.

**Comment by A6GibKm** [comment]
See https://github.com/flathub/cc.arduino.arduinoide/pull/31/commits/4f2f562dd153d527c3b9d09b4fe9064f14afa464 for a concrete update.
