### ISSUE TITLE
Outdated version

### ISSUE THREAD

**Issue by kolgza** [flathub/cc.arduino.arduinoide#9]
The current version of Arduino IDE is 1.8.9, but Flathub only has 1.8.5.

**Comment by muelli** [comment]
for the next time: if you provide a reference, maybe even a download URL, then you make it much easier for a casual drive-by contributor to send patches.

https://github.com/arduino/Arduino/releases/

The appdata file is patched, rather than copied over, which arguably makes bumping the version a bit harder.  Also, there are many dependencies of which it is a bit unclear whether they need to be bumped, too.

**Comment by A6GibKm** [comment]
Fixed in #11 , #12

**Comment by merwok** [comment]
Thanks!
